### ISSUE TITLE
启动时验证缓存完整性报错

### ISSUE THREAD

**Issue by VCE1** [taskmgr818/hath-with-natter#1]
平台：Ubuntu22.04，架构：x86_64
运行方式：Python3

今天设备突然下线了，原因是代理出了问题，更换代理后仍无法启动，客户端似乎无法正常进行缓存校验？

启动后可以正常通信e-hentai.org，然后会先进行缓存校验，但进行校验时会提示`INFO - HTTP Request: GET https://223.5.5.5 "HTTP/1.1 404 Not Found"`

随后会进行重启，但结果一样出现这个报错。
![image](https://github.com/taskmgr818/hath-with-natter/assets/79588027/b776a475-5787-4461-a2de-721da2ecc33d)
![image](https://github.com/taskmgr818/hath-with-natter/assets/79588027/96b6c990-b977-442c-a0ed-102008bf001d)

我的解决方法是去[Hentai@Home](https://e-hentai.org/hentaiathome.php)客户端设置中手动关闭客户端的验证缓存完整性（去掉勾选），然后就能正常运行了。
![image](https://github.com/taskmgr818/hath-with-natter/assets/79588027/4d267b65-101e-4ab5-b210-d276470e2ae8)
感觉可能是客户端问题，虽然缓存校验用不上，但还是先提一下。

**Comment by taskmgr818** [comment]
`INFO - HTTP Request: GET https://223.5.5.5 "HTTP/1.1 404 Not Found"`
这个其实是在客户端掉线后用来检测网络是否正常的，我偷懒直接写成get了，所以会报404，是正常现象。

我猜可能是hath-rust校验缓存的时间比较长，导致main.py在一定时间内没有检测到端口开放，误判为启动失败，自动重启了（重启前会检测网络连接，所以会有上述报错）。
